opendnp3: openpal Namespace Reference
openpal Namespace Reference
Namespaces
logflags
sizes
Classes
class Array
Template type for a dynamically allocated array.
class ArrayView
Acts as a safe facade around an underlying array.
class Bit16LE
class Bit32LE
class Buffer
class DoubleFloat
class FixedUTCTimeSource
Mock usable for testing.
struct FloatByteOrder
class Format
class HasSize
class IChannelState
class IExecutor
Interface for posting events to a queue.
class ILogHandler
Callback interface for log messages.
class IMonotonicTimeSource
class IPhysicalLayer
Defines an asynchronous interface for serial/tcp/?
class IPhysicalLayerCallbacks
class ITimer
Timer are used to defer events for a later time on an executor.
class IUTCTimeSource
Interface that defines a method to get UTC timestamps.
class LogEntry
An event recorded by the logging framework.
class LogFilters
Strongly typed wrapper for flags bitfield.
class Logger
A copyable facade over a LogRoot class.
class MonotonicTimestamp
Strong typing for millisecond-based monotonic timestamps.
class Pair
class Parse
class RAII
Finally is an RAII helper that takes a functor to run when it destructs.
class RSlice
Represents a readonly slice of a buffer located elsewhere.
class SequenceNum
represents a sequence number
class Serializer
class Settable
class SingleFloat
class StaticBuffer
class StaticOnly
class TimeDuration
Strong typing for millisecond based time durations.
class TimeDurationBase
class TimerRef
A management class to make dealing with timer pointers safer a little safer.
class UInt48LE
class UInt48Type
class UInt8Simple
class Uncopyable
Inherited classes will not have default copy/assignment.
class UTCTimestamp
Strong typing for UTCTimestamps.
class WSlice
Represents a write-able slice of a buffer located elsewhere.
Typedefs
typedef std::function< void()> action_t
typedef Bit16LE< int16_t > Int16
typedef Bit32LE< int32_t > Int32
typedef Bit16LE< uint16_t > UInt16
typedef Bit32LE< uint32_t > UInt32
typedef UInt48LE UInt48
typedef UInt8Simple UInt8
Functions
char * AllocateCopy (char const *src)
template<class T >
T Bounded (T value, T min, T max)
template<typename Cleanup >
RAII< Cleanup > Finally (const Cleanup &)
template<class T >
bool FloatEqual (T a, T b, T eapllon=1e-6)
void LogHex (Logger &logger, const openpal::LogFilters &filters, const openpal::RSlice &source, uint32_t firstRowSize, uint32_t otherRowSize)
template<class T >
T Max (T a, T b)
template<class T >
T MaxValue ()
template<class T >
T Min (T a, T b)
template<class T >
T MinValue ()
bool operator< (const MonotonicTimestamp &first, const MonotonicTimestamp &second)
bool operator== (const MonotonicTimestamp &first, const MonotonicTimestamp &second)
bool operator== (const TimeDuration &lhs, const TimeDuration &rhs)
bool operator> (const MonotonicTimestamp &first, const MonotonicTimestamp &second)
char ToHexChar (char c)
template<class T >
bool WithinLimits (T value, T min, T max)
Variables
const uint32_t MAX_HEX_PER_LINE = 20
const uint32_t MAX_LOG_ENTRY_SIZE = 120
Detailed Description
Some docs here for openpal
Typedef Documentation
action_t
typedef std::function<void()> openpal::action_t
Definition at line 32 of file IExecutor.h.
Int16
typedef Bit16LE<int16_t> openpal::Int16
Definition at line 32 of file Serialization.h.
Int32
typedef Bit32LE<int32_t> openpal::Int32
Definition at line 34 of file Serialization.h.
UInt16
typedef Bit16LE<uint16_t> openpal::UInt16
Definition at line 33 of file Serialization.h.
UInt32
typedef Bit32LE<uint32_t> openpal::UInt32
Definition at line 35 of file Serialization.h.
UInt48
typedef UInt48LE openpal::UInt48
Definition at line 36 of file Serialization.h.
UInt8
typedef UInt8Simple openpal::UInt8
Definition at line 37 of file Serialization.h.
Function Documentation
AllocateCopy()
char* openpal::AllocateCopy (char const * src)
Bounded()
template<class T > T openpal::Bounded (T value, T min, T max) inline
Definition at line 36 of file Comparisons.h.
References Max(), and Min().
Finally()
template<typename Cleanup > RAII< Cleanup > openpal::Finally (const Cleanup & fun)
Definition at line 52 of file Finally.h.
FloatEqual()
template<class T > bool openpal::FloatEqual (T a, T b, T eapllon = 1e-6)
Definition at line 46 of file Comparisons.h.
LogHex()
void openpal::LogHex (Logger & logger, const openpal::LogFilters & filters, const openpal::RSlice & source, uint32_t firstRowSize, uint32_t otherRowSize)
Max()
template<class T > T openpal::Max (T a, T b) inline
Definition at line 31 of file Comparisons.h.
Referenced by Bounded().
MaxValue()
template<class T > T openpal::MaxValue ()
Min()
template<class T > T openpal::Min (T a, T b) inline
Definition at line 26 of file Comparisons.h.
Referenced by Bounded(), openpal::StaticBuffer< MAX_SIZE >::GetWSlice(), and openpal::StaticBuffer< MAX_SIZE >::ToRSlice().
MinValue()
template<class T > T openpal::MinValue ()
operator<()
bool openpal::operator< (const MonotonicTimestamp & first, const MonotonicTimestamp & second)
operator==() [1/2]
bool openpal::operator== (const MonotonicTimestamp & first, const MonotonicTimestamp & second)
operator==() [2/2]
bool openpal::operator== (const TimeDuration & lhs, const TimeDuration & rhs)
operator>()
bool openpal::operator> (const MonotonicTimestamp & first, const MonotonicTimestamp & second)
ToHexChar()
char openpal::ToHexChar (char c)
WithinLimits()
template<class T > bool openpal::WithinLimits (T value, T min, T max) inline
Definition at line 41 of file Comparisons.h.
Variable Documentation
MAX_HEX_PER_LINE
const uint32_t openpal::MAX_HEX_PER_LINE = 20
Definition at line 30 of file StringFormatting.h.
MAX_LOG_ENTRY_SIZE
const uint32_t openpal::MAX_LOG_ENTRY_SIZE = 120
Definition at line 29 of file StringFormatting.h.