opendnp3: asiodnp3::IListenCallbacks::~IListenCallbacks
virtual asiodnp3::IListenCallbacks::~IListenCallbacks () inline virtual
Definition at line 40 of file IListenCallbacks.h.
References AcceptCertificate(), AcceptConnection(), GetFirstFrameTimeout(), OnCertificateError(), OnConnectionClose(), and OnFirstFrame().
 {}