opendnp3: openpal::RingBuffer::Count
template<uint8_t N> volatile uint8_t openpal::RingBuffer< N >::Count () inline private
Definition at line 110 of file RingBuffer.h.
References openpal::RingBuffer< N >::head, and openpal::RingBuffer< N >::tail.
Referenced by openpal::RingBuffer< N >::Empty(), openpal::RingBuffer< N >::Full(), openpal::RingBuffer< N >::GetMany(), and openpal::RingBuffer< N >::PutMany().
     {
         return head - tail;
     }