opendnp3: openpal::Min
template<class T > T openpal::Min (T a, T b) inline
Definition at line 28 of file Comparisons.h.
Referenced by Bounded(), openpal::StaticBuffer< MAX_SIZE >::GetWSlice(), openpal::TimeDuration::MultiplyBy(), and openpal::StaticBuffer< MAX_SIZE >::ToRSlice().
 {
     return (a < b) ? a : b;
 }