opendnp3: openpal::RSlice::Advance
void openpal::RSlice::Advance (uint32_t count)
Referenced by openpal::RingBuffer< N >::PutMany(), openpal::UInt8Simple::ReadBuffer(), openpal::UInt48LE::ReadBuffer(), openpal::Bit16LE< T >::ReadBuffer(), and openpal::Bit32LE< T >::ReadBuffer().