opendnp3: openpal::RSlice Class Reference
openpal::RSlice Class Reference
Represents a readonly slice of a buffer located elsewhere.
#include <RSlice.h>
Public Member Functions
RSlice ()
RSlice (uint8_t const *pBuffer, uint32_t size)
void Advance (uint32_t count)
void Clear ()
RSlice CopyTo (WSlice &) const
bool Equals (const RSlice &rhs) const
operator uint8_t const * () const
RSlice Skip (uint32_t count) const
RSlice Take (uint32_t count) const
Public Member Functions inherited from openpal::HasSize< uint32_t >
HasSize (uint32_t size)
bool IsEmpty () const
bool IsNotEmpty () const
uint32_t Size () const
Static Public Member Functions
static RSlice Empty ()
Private Attributes
uint8_t const * pBuffer
Additional Inherited Members
Protected Attributes inherited from openpal::HasSize< uint32_t >
uint32_t size
Detailed Description
Represents a readonly slice of a buffer located elsewhere.
Mediates reading from the buffer to prevent overreads and other errors.
Definition at line 36 of file RSlice.h.
Constructor & Destructor Documentation
RSlice() [1/2]
openpal::RSlice::RSlice ()
RSlice() [2/2]
openpal::RSlice::RSlice (uint8_t const * pBuffer, uint32_t size)
Member Function Documentation
Advance()
void openpal::RSlice::Advance (uint32_t count)
Referenced by openpal::UInt8Simple::ReadBuffer(), openpal::UInt48LE::ReadBuffer(), openpal::Bit16LE< T >::ReadBuffer(), and openpal::Bit32LE< T >::ReadBuffer().
Clear()
void openpal::RSlice::Clear ()
CopyTo()
RSlice openpal::RSlice::CopyTo (WSlice &) const
Empty()
static RSlice openpal::RSlice::Empty () static
Equals()
bool openpal::RSlice::Equals (const RSlice & rhs) const
Referenced by opendnp3::OctetStringSpec::IsEvent().
operator uint8_t const *()
openpal::RSlice::operator uint8_t const * () const inline
Definition at line 58 of file RSlice.h.
References pBuffer.
Skip()
RSlice openpal::RSlice::Skip (uint32_t count) const
Take()
RSlice openpal::RSlice::Take (uint32_t count) const
Member Data Documentation
pBuffer
uint8_t const* openpal::RSlice::pBuffer private
Definition at line 64 of file RSlice.h.
Referenced by operator uint8_t const *().
The documentation for this class was generated from the following file:
cpp/libs/include/openpal/container/RSlice.h