opendnp3: asiodnp3::IStack::~IStack
virtual asiodnp3::IStack::~IStack () inline virtual
Definition at line 38 of file IStack.h.
References Disable(), Enable(), and GetStackStatistics().
 {}