opendnp3: openpal::Bit16LE< T > Class Template Reference
openpal::Bit16LE< T > Class Template Reference
#include <SerializationTemplatesLE.h>
Public Types
typedef T Type
Static Public Member Functions
static T Read (const uint8_t *data)
static T ReadBuffer (RSlice &arBuffer)
static void Write (uint8_t *data, T value)
static void WriteBuffer (WSlice &buffer, T aValue)
Static Public Attributes
const static T Max = openpal::MaxValue<T>()
const static T Min = openpal::MinValue<T>()
const static size_t SIZE = sizeof(T)
Detailed Description
template<class T>
class openpal::Bit16LE< T >
Definition at line 33 of file SerializationTemplatesLE.h.
Member Typedef Documentation
Type
template<class T > typedef T openpal::Bit16LE< T >::Type
Definition at line 60 of file SerializationTemplatesLE.h.
Member Function Documentation
Read()
template<class T > static T openpal::Bit16LE< T >::Read (const uint8_t * data) inline static
Definition at line 36 of file SerializationTemplatesLE.h.
Referenced by openpal::Bit16LE< T >::ReadBuffer().
ReadBuffer()
template<class T > static T openpal::Bit16LE< T >::ReadBuffer (RSlice & arBuffer) inline static
Definition at line 53 of file SerializationTemplatesLE.h.
References openpal::RSlice::Advance(), openpal::Bit16LE< T >::Read(), and openpal::Bit16LE< T >::SIZE.
Write()
template<class T > static void openpal::Bit16LE< T >::Write (uint8_t * data, T value) inline static
Definition at line 41 of file SerializationTemplatesLE.h.
Referenced by openpal::Bit16LE< T >::WriteBuffer().
WriteBuffer()
template<class T > static void openpal::Bit16LE< T >::WriteBuffer (WSlice & buffer, T aValue) inline static
Definition at line 47 of file SerializationTemplatesLE.h.
References openpal::WSlice::Advance(), openpal::Bit16LE< T >::SIZE, and openpal::Bit16LE< T >::Write().
Member Data Documentation
Max
template<class T > const T openpal::Bit16LE< T >::Max = openpal::MaxValue<T>() static
Definition at line 63 of file SerializationTemplatesLE.h.
Min
template<class T > const T openpal::Bit16LE< T >::Min = openpal::MinValue<T>() static
Definition at line 64 of file SerializationTemplatesLE.h.
SIZE
template<class T > const static size_t openpal::Bit16LE< T >::SIZE = sizeof(T) static
Definition at line 62 of file SerializationTemplatesLE.h.
Referenced by openpal::Bit16LE< T >::ReadBuffer(), and openpal::Bit16LE< T >::WriteBuffer().
The documentation for this class was generated from the following file:
cpp/libs/include/openpal/serialization/SerializationTemplatesLE.h