opendnp3: opendnp3::IPEndpoint Struct Reference
opendnp3::IPEndpoint Struct Reference
#include <opendnp3/channel/IPEndpoint.h>
Public Member Functions
IPEndpoint (const std::string &address, uint16_t port)
Static Public Member Functions
static IPEndpoint AllAdapters (uint16_t port)
static IPEndpoint Localhost (uint16_t port)
Public Attributes
std::string address
uint16_t port
Detailed Description
Definition at line 29 of file IPEndpoint.h.
Constructor & Destructor Documentation
IPEndpoint()
opendnp3::IPEndpoint::IPEndpoint (const std::string & address, uint16_t port) inline
Definition at line 31 of file IPEndpoint.h.
Referenced by AllAdapters(), and Localhost().
Member Function Documentation
AllAdapters()
static IPEndpoint opendnp3::IPEndpoint::AllAdapters (uint16_t port) inline static
Definition at line 33 of file IPEndpoint.h.
References IPEndpoint(), and port.
Localhost()
static IPEndpoint opendnp3::IPEndpoint::Localhost (uint16_t port) inline static
Definition at line 38 of file IPEndpoint.h.
References IPEndpoint(), and port.
Member Data Documentation
address
std::string opendnp3::IPEndpoint::address
Definition at line 43 of file IPEndpoint.h.
port
uint16_t opendnp3::IPEndpoint::port
Definition at line 44 of file IPEndpoint.h.
Referenced by AllAdapters(), and Localhost().
The documentation for this struct was generated from the following file:
opendnp3/channel/IPEndpoint.h