opendnp3: asiodnp3::IChannel::~IChannel
virtual asiodnp3::IChannel::~IChannel () inline virtual
Definition at line 55 of file IChannel.h.
References AddMaster(), AddOutstation(), GetLogFilters(), GetStatistics(), and SetLogFilters().
 {}