opendnp3: asiodnp3::IMasterOperations::~IMasterOperations
virtual asiodnp3::IMasterOperations::~IMasterOperations () inline virtual
Definition at line 54 of file IMasterOperations.h.
References AddAllObjectsScan(), AddClassScan(), AddRangeScan(), AddScan(), opendnp3::TaskConfig::Default(), PerformFunction(), Restart(), Scan(), ScanAllObjects(), ScanClasses(), ScanRange(), SetLogFilters(), and Write().
 {}