opendnp3: opendnp3::LogLevels Class Reference
opendnp3::LogLevels Class Reference
Strongly typed wrapper for flags bitfield.
#include <opendnp3/logging/LogLevels.h>
Public Member Functions
LogLevels ()=default
LogLevels (int32_t levels)
LogLevels (LogLevel level)
int32_t get_value () const
bool is_set (const LogLevel &level) const
LogLevels operator| (const LogLevel &other) const
LogLevels operator| (const LogLevels &other) const
LogLevels & operator|= (const LogLevel &other)
LogLevels & operator|= (const LogLevels &other)
LogLevels operator~ () const
Static Public Member Functions
static LogLevels everything ()
static LogLevels none ()
Private Attributes
int32_t levels = 0
Detailed Description
Strongly typed wrapper for flags bitfield.
Definition at line 61 of file LogLevels.h.
Constructor & Destructor Documentation
LogLevels() [1/3]
opendnp3::LogLevels::LogLevels () default
Referenced by everything(), none(), operator|(), and operator~().
LogLevels() [2/3]
opendnp3::LogLevels::LogLevels (int32_t levels) inline explicit
Definition at line 66 of file LogLevels.h.
LogLevels() [3/3]
opendnp3::LogLevels::LogLevels (LogLevel level) inline
Definition at line 68 of file LogLevels.h.
Member Function Documentation
everything()
static LogLevels opendnp3::LogLevels::everything () inline static
Definition at line 75 of file LogLevels.h.
References LogLevels().
get_value()
int32_t opendnp3::LogLevels::get_value () const inline
Definition at line 112 of file LogLevels.h.
References levels.
is_set()
bool opendnp3::LogLevels::is_set (const LogLevel & level) const inline
Definition at line 80 of file LogLevels.h.
References levels, and opendnp3::LogLevel::value.
none()
static LogLevels opendnp3::LogLevels::none () inline static
Definition at line 70 of file LogLevels.h.
References LogLevels().
operator|() [1/2]
LogLevels opendnp3::LogLevels::operator| (const LogLevel & other) const inline
Definition at line 96 of file LogLevels.h.
References levels, LogLevels(), and opendnp3::LogLevel::value.
operator|() [2/2]
LogLevels opendnp3::LogLevels::operator| (const LogLevels & other) const inline
Definition at line 107 of file LogLevels.h.
References levels, and LogLevels().
operator|=() [1/2]
LogLevels& opendnp3::LogLevels::operator|= (const LogLevel & other) inline
Definition at line 90 of file LogLevels.h.
References levels, and opendnp3::LogLevel::value.
operator|=() [2/2]
LogLevels& opendnp3::LogLevels::operator|= (const LogLevels & other) inline
Definition at line 101 of file LogLevels.h.
References levels.
operator~()
LogLevels opendnp3::LogLevels::operator~ () const inline
Definition at line 85 of file LogLevels.h.
References levels, and LogLevels().
Member Data Documentation
levels
int32_t opendnp3::LogLevels::levels = 0 private
Definition at line 118 of file LogLevels.h.
Referenced by get_value(), is_set(), operator|(), operator|=(), and operator~().
The documentation for this class was generated from the following file:
opendnp3/logging/LogLevels.h