opendnp3: asiopal::IPEndpoint Struct Reference
asiopal::IPEndpoint Struct Reference
#include <IPEndpoint.h>
Public Member Functions
IPEndpoint (const std::string &address, uint16_t port)
Static Public Member Functions
static IPEndpoint AllAdapters (uint16_t port)
static IPEndpoint Localhost (uint16_t port)
Public Attributes
std::string address
uint16_t port
Detailed Description
Definition at line 31 of file IPEndpoint.h.
Constructor & Destructor Documentation
IPEndpoint()
asiopal::IPEndpoint::IPEndpoint (const std::string & address, uint16_t port) inline
Definition at line 33 of file IPEndpoint.h.
Referenced by AllAdapters(), and Localhost().
Member Function Documentation
AllAdapters()
static IPEndpoint asiopal::IPEndpoint::AllAdapters (uint16_t port) inline static
Definition at line 35 of file IPEndpoint.h.
References IPEndpoint(), and port.
Localhost()
static IPEndpoint asiopal::IPEndpoint::Localhost (uint16_t port) inline static
Definition at line 40 of file IPEndpoint.h.
References IPEndpoint(), and port.
Member Data Documentation
address
std::string asiopal::IPEndpoint::address
Definition at line 45 of file IPEndpoint.h.
port
uint16_t asiopal::IPEndpoint::port
Definition at line 46 of file IPEndpoint.h.
Referenced by AllAdapters(), and Localhost().
The documentation for this struct was generated from the following file:
cpp/libs/include/asiopal/IPEndpoint.h