opendnp3: openpal::Logger Class Reference
openpal::Logger Class Reference
A copyable facade over a LogRoot class.
#include <Logger.h>
Classes
struct Settings
Public Member Functions
Logger (std::shared_ptr< ILogHandler > backend, const std::string &id, openpal::LogFilters levels)
Logger Detach (const std::string &id) const
Logger Detach (const std::string &id, openpal::LogFilters levels) const
Logger Detach (openpal::LogFilters levels) const
LogFilters GetFilters () const
bool IsEnabled (const LogFilters &filters) const
void Log (const LogFilters &filters, const char *location, const char *message)
void Rename (const std::string &id)
void SetFilters (const openpal::LogFilters &filters)
Static Public Member Functions
static Logger Empty ()
Private Member Functions
Logger ()=delete
Logger (const std::shared_ptr< ILogHandler > &backend, const std::shared_ptr< Settings > &settings)
Logger & operator= (const Logger &)=delete
Private Attributes
const std::shared_ptr< ILogHandler > backend
const std::shared_ptr< Settings > settings
Detailed Description
A copyable facade over a LogRoot class.
Definition at line 34 of file Logger.h.
Constructor & Destructor Documentation
Logger() [1/3]
openpal::Logger::Logger (std::shared_ptr< ILogHandler > backend, const std::string & id, openpal::LogFilters levels)
Logger() [2/3]
openpal::Logger::Logger (const std::shared_ptr< ILogHandler > & backend, const std::shared_ptr< Settings > & settings) inline private
Definition at line 88 of file Logger.h.
Logger() [3/3]
openpal::Logger::Logger () private delete
Referenced by Detach(), and Empty().
Member Function Documentation
Detach() [1/3]
Logger openpal::Logger::Detach (const std::string & id) const inline
Definition at line 55 of file Logger.h.
References backend, Logger(), and settings.
Detach() [2/3]
Logger openpal::Logger::Detach (const std::string & id, openpal::LogFilters levels) const inline
Definition at line 60 of file Logger.h.
References backend, and Logger().
Detach() [3/3]
Logger openpal::Logger::Detach (openpal::LogFilters levels) const inline
Definition at line 65 of file Logger.h.
References backend, Logger(), and settings.
Empty()
static Logger openpal::Logger::Empty () inline static
Definition at line 48 of file Logger.h.
References Logger().
GetFilters()
LogFilters openpal::Logger::GetFilters () const inline
Definition at line 72 of file Logger.h.
References settings.
IsEnabled()
bool openpal::Logger::IsEnabled (const LogFilters & filters) const
Log()
void openpal::Logger::Log (const LogFilters & filters, const char * location, const char * message)
operator=()
Logger& openpal::Logger::operator= (const Logger &) private delete
Rename()
void openpal::Logger::Rename (const std::string & id) inline
Definition at line 82 of file Logger.h.
References settings.
SetFilters()
void openpal::Logger::SetFilters (const openpal::LogFilters & filters) inline
Definition at line 77 of file Logger.h.
References settings.
Member Data Documentation
backend
const std::shared_ptr<ILogHandler> openpal::Logger::backend private
Definition at line 96 of file Logger.h.
Referenced by Detach().
settings
const std::shared_ptr<Settings> openpal::Logger::settings private
Definition at line 97 of file Logger.h.
Referenced by Detach(), GetFilters(), Rename(), and SetFilters().
The documentation for this class was generated from the following file:
cpp/libs/include/openpal/logging/Logger.h