opendnp3: asiodnp3::IOutstation::~IOutstation
virtual asiodnp3::IOutstation::~IOutstation () inline virtual
Definition at line 41 of file IOutstation.h.
References Apply(), SetLogFilters(), and SetRestartIIN().
 {}