opendnp3: opendnp3::TaskConfig Class Reference
opendnp3::TaskConfig Class Reference
Object containing multiple fields for configuring tasks.
#include <TaskConfig.h>
Public Member Functions
TaskConfig ()=delete
TaskConfig (TaskId taskId, ITaskCallback *pCallback)
Static Public Member Functions
static TaskConfig Default ()
static TaskConfig With (ITaskCallback &callback)
— syntax sugar for building configs --—
Public Attributes
ITaskCallback * pCallback
TaskId taskId
Detailed Description
Object containing multiple fields for configuring tasks.
Definition at line 34 of file TaskConfig.h.
Constructor & Destructor Documentation
TaskConfig() [1/2]
opendnp3::TaskConfig::TaskConfig (TaskId taskId, ITaskCallback * pCallback) inline
Definition at line 37 of file TaskConfig.h.
TaskConfig() [2/2]
opendnp3::TaskConfig::TaskConfig () delete
Referenced by Default(), and With().
Member Function Documentation
Default()
static TaskConfig opendnp3::TaskConfig::Default () inline static
Definition at line 39 of file TaskConfig.h.
References TaskConfig(), and opendnp3::TaskId::Undefined().
With()
static TaskConfig opendnp3::TaskConfig::With (ITaskCallback & callback) inline static
— syntax sugar for building configs --—
Definition at line 46 of file TaskConfig.h.
References TaskConfig(), and opendnp3::TaskId::Undefined().
Member Data Documentation
pCallback
ITaskCallback* opendnp3::TaskConfig::pCallback
Definition at line 55 of file TaskConfig.h.
taskId
TaskId opendnp3::TaskConfig::taskId
Definition at line 54 of file TaskConfig.h.
The documentation for this class was generated from the following file:
cpp/libs/include/opendnp3/master/TaskConfig.h