opendnp3: opendnp3::DatabaseSizes::DatabaseSizes
opendnp3::DatabaseSizes::DatabaseSizes (uint16_t numBinary, uint16_t numDoubleBinary, uint16_t numAnalog, uint16_t numCounter, uint16_t numFrozenCounter, uint16_t numBinaryOutputStatus, uint16_t numAnalogOutputStatus, uint16_t numTimeAndInterval) inline
Definition at line 84 of file DatabaseSizes.h.
Referenced by AllTypes(), AnalogOnly(), AnalogOutputStatusOnly(), BinaryOnly(), BinaryOutputStatusOnly(), CounterOnly(), DoubleBinaryOnly(), Empty(), FrozenCounterOnly(), and TimeAndIntervalOnly().
                                                :
         numBinary(numBinary),
         numDoubleBinary(numDoubleBinary),
         numAnalog(numAnalog),
         numCounter(numCounter),
         numFrozenCounter(numFrozenCounter),
         numBinaryOutputStatus(numBinaryOutputStatus),
         numAnalogOutputStatus(numAnalogOutputStatus),
         numTimeAndInterval(numTimeAndInterval)
     {}