opendnp3: opendnp3::StaticTypeBitField Struct Reference
opendnp3::StaticTypeBitField Struct Reference
A bitfield that describes a subset of all static types, e.g.
#include <opendnp3/outstation/StaticTypeBitfield.h>
Public Member Functions
StaticTypeBitField ()
StaticTypeBitField (uint16_t mask)
StaticTypeBitField Except (StaticTypeBitmask type) const
bool IsSet (StaticTypeBitmask type) const
Static Public Member Functions
static StaticTypeBitField AllTypes ()
Private Attributes
uint16_t mask
Detailed Description
A bitfield that describes a subset of all static types, e.g.
{ Binary, Analog } or {Analog, Counter, FrozenCounter }
Definition at line 33 of file StaticTypeBitfield.h.
Constructor & Destructor Documentation
StaticTypeBitField() [1/2]
opendnp3::StaticTypeBitField::StaticTypeBitField () inline
Definition at line 35 of file StaticTypeBitfield.h.
Referenced by AllTypes(), and Except().
StaticTypeBitField() [2/2]
opendnp3::StaticTypeBitField::StaticTypeBitField (uint16_t mask) inline
Definition at line 37 of file StaticTypeBitfield.h.
Member Function Documentation
AllTypes()
static StaticTypeBitField opendnp3::StaticTypeBitField::AllTypes () inline static
Definition at line 39 of file StaticTypeBitfield.h.
References StaticTypeBitField().
Except()
StaticTypeBitField opendnp3::StaticTypeBitField::Except (StaticTypeBitmask type) const inline
Definition at line 49 of file StaticTypeBitfield.h.
References mask, and StaticTypeBitField().
IsSet()
bool opendnp3::StaticTypeBitField::IsSet (StaticTypeBitmask type) const inline
Definition at line 44 of file StaticTypeBitfield.h.
References mask.
Member Data Documentation
mask
uint16_t opendnp3::StaticTypeBitField::mask private
Definition at line 55 of file StaticTypeBitfield.h.
Referenced by Except(), and IsSet().
The documentation for this struct was generated from the following file:
opendnp3/outstation/StaticTypeBitfield.h