opendnp3: opendnp3::TaskId::Undefined
static TaskId opendnp3::TaskId::Undefined () inline static
Definition at line 38 of file TaskId.h.
References TaskId().
Referenced by opendnp3::TaskConfig::Default(), and opendnp3::TaskConfig::With().
     {
         return TaskId(-1, false);
     }