opendnp3: opendnp3::TaskId Class Reference
opendnp3::TaskId Class Reference
Interface that represents a running master.
#include <TaskId.h>
Public Member Functions
int GetId () const
bool IsDefined () const
Static Public Member Functions
static TaskId Defined (int id)
static TaskId Undefined ()
Private Member Functions
TaskId ()=delete
TaskId (int id_, bool isDefined_)
Private Attributes
int id
bool isDefined
Detailed Description
Interface that represents a running master.
Definition at line 29 of file TaskId.h.
Constructor & Destructor Documentation
TaskId() [1/2]
opendnp3::TaskId::TaskId () private delete
Referenced by Defined(), and Undefined().
TaskId() [2/2]
opendnp3::TaskId::TaskId (int id_, bool isDefined_) inline private
Definition at line 53 of file TaskId.h.
Member Function Documentation
Defined()
static TaskId opendnp3::TaskId::Defined (int id) inline static
Definition at line 32 of file TaskId.h.
References TaskId().
GetId()
int opendnp3::TaskId::GetId () const inline
Definition at line 41 of file TaskId.h.
References id.
IsDefined()
bool opendnp3::TaskId::IsDefined () const inline
Definition at line 45 of file TaskId.h.
References isDefined.
Undefined()
static TaskId opendnp3::TaskId::Undefined () inline static
Definition at line 36 of file TaskId.h.
References TaskId().
Referenced by opendnp3::TaskConfig::Default(), and opendnp3::TaskConfig::With().
Member Data Documentation
id
int opendnp3::TaskId::id private
Definition at line 55 of file TaskId.h.
Referenced by GetId().
isDefined
bool opendnp3::TaskId::isDefined private
Definition at line 56 of file TaskId.h.
Referenced by IsDefined().
The documentation for this class was generated from the following file:
cpp/libs/include/opendnp3/master/TaskId.h