opendnp3: opendnp3::CommandSet::Add
template<class T > void opendnp3::CommandSet::Add (std::vector< Indexed< T >> items) inline
Convenience functions that can build an entire header in one call.
Definition at line 90 of file CommandSet.h.
References AddAny(), CommandSet(), operator=(), StartHeader(), StartHeaderAODouble64(), StartHeaderAOFloat32(), StartHeaderAOInt16(), StartHeaderAOInt32(), and StartHeaderCROB().
     {
         if (!items.empty())
         {
             auto& header = this->StartHeader<T>();
             for (auto& command : items)
             {
                 header.Add(command.value, command.index);
             }
         }
     }