opendnp3: openpal::SequenceNum< T, Modulus > Class Template Reference
openpal::SequenceNum< T, Modulus > Class Template Reference
represents a sequence number
#include <SequenceNum.h>
Public Member Functions
SequenceNum ()
SequenceNum (T value)
bool Equals (T other) const
uint8_t Get () const
void Increment ()
SequenceNum Next () const
operator uint8_t () const
void Reset ()
Protected Attributes
T seq
Static Private Member Functions
static T Next (T seq)
Detailed Description
template<class T, T Modulus>
class openpal::SequenceNum< T, Modulus >
represents a sequence number
Definition at line 28 of file SequenceNum.h.
Constructor & Destructor Documentation
SequenceNum() [1/2]
template<class T , T Modulus> openpal::SequenceNum< T, Modulus >::SequenceNum () inline
Definition at line 46 of file SequenceNum.h.
Referenced by openpal::SequenceNum< T, Modulus >::Next().
SequenceNum() [2/2]
template<class T , T Modulus> openpal::SequenceNum< T, Modulus >::SequenceNum (T value) inline
Definition at line 48 of file SequenceNum.h.
Member Function Documentation
Equals()
template<class T , T Modulus> bool openpal::SequenceNum< T, Modulus >::Equals (T other) const inline
Definition at line 50 of file SequenceNum.h.
References openpal::SequenceNum< T, Modulus >::seq.
Get()
template<class T , T Modulus> uint8_t openpal::SequenceNum< T, Modulus >::Get () const inline
Definition at line 36 of file SequenceNum.h.
References openpal::SequenceNum< T, Modulus >::seq.
Increment()
template<class T , T Modulus> void openpal::SequenceNum< T, Modulus >::Increment () inline
Definition at line 55 of file SequenceNum.h.
References openpal::SequenceNum< T, Modulus >::Next(), and openpal::SequenceNum< T, Modulus >::seq.
Next() [1/2]
template<class T , T Modulus> SequenceNum openpal::SequenceNum< T, Modulus >::Next () const inline
Definition at line 65 of file SequenceNum.h.
References openpal::SequenceNum< T, Modulus >::seq, and openpal::SequenceNum< T, Modulus >::SequenceNum().
Referenced by openpal::SequenceNum< T, Modulus >::Increment().
Next() [2/2]
template<class T , T Modulus> static T openpal::SequenceNum< T, Modulus >::Next (T seq) inline static private
Definition at line 30 of file SequenceNum.h.
References openpal::SequenceNum< T, Modulus >::seq.
operator uint8_t()
template<class T , T Modulus> openpal::SequenceNum< T, Modulus >::operator uint8_t () const inline
Definition at line 41 of file SequenceNum.h.
References openpal::SequenceNum< T, Modulus >::seq.
Reset()
template<class T , T Modulus> void openpal::SequenceNum< T, Modulus >::Reset () inline
Definition at line 60 of file SequenceNum.h.
References openpal::SequenceNum< T, Modulus >::seq.
Member Data Documentation
seq
template<class T , T Modulus> T openpal::SequenceNum< T, Modulus >::seq protected
Definition at line 71 of file SequenceNum.h.
Referenced by openpal::SequenceNum< T, Modulus >::Equals(), openpal::SequenceNum< T, Modulus >::Get(), openpal::SequenceNum< T, Modulus >::Increment(), openpal::SequenceNum< T, Modulus >::Next(), openpal::SequenceNum< T, Modulus >::operator uint8_t(), and openpal::SequenceNum< T, Modulus >::Reset().
The documentation for this class was generated from the following file:
cpp/libs/include/openpal/util/SequenceNum.h