opendnp3: opendnp3::PrintingSOEHandler Class Reference
opendnp3::PrintingSOEHandler Class Reference final
ISOEHandler singleton that prints to the console.
#include <opendnp3/master/PrintingSOEHandler.h>
Public Member Functions
PrintingSOEHandler ()
void BeginFragment (const ResponseInfo &info) override
void EndFragment (const ResponseInfo &info) override
virtual void Process (const HeaderInfo &info, const ICollection< DNPTime > &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< Analog >> &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< AnalogCommandEvent >> &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< AnalogOutputStatus >> &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< Binary >> &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< BinaryCommandEvent >> &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< BinaryOutputStatus >> &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< Counter >> &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< DoubleBitBinary >> &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< FrozenCounter >> &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< OctetString >> &values) override
virtual void Process (const HeaderInfo &info, const ICollection< Indexed< TimeAndInterval >> &values) override
Public Member Functions inherited from opendnp3::ISOEHandler
virtual ~ISOEHandler ()=default
Static Public Member Functions
static std::shared_ptr< ISOEHandler > Create ()
Static Private Member Functions
static std::string GetTimeString (TimestampQuality tsquality)
template<class T >
static void Print (const HeaderInfo &info, const T &value, uint16_t index)
template<class T >
static void PrintAll (const HeaderInfo &info, const ICollection< Indexed< T >> &values)
static std::string ValueToString (const DoubleBitBinary &meas)
template<class T >
static std::string ValueToString (const T &meas)
Detailed Description
ISOEHandler singleton that prints to the console.
Definition at line 35 of file PrintingSOEHandler.h.
Constructor & Destructor Documentation
PrintingSOEHandler()
opendnp3::PrintingSOEHandler::PrintingSOEHandler () inline
Definition at line 39 of file PrintingSOEHandler.h.
Member Function Documentation
BeginFragment()
void opendnp3::PrintingSOEHandler::BeginFragment (const ResponseInfo & info) override virtual
Implements opendnp3::ISOEHandler.
Create()
static std::shared_ptr<ISOEHandler> opendnp3::PrintingSOEHandler::Create () inline static
Definition at line 41 of file PrintingSOEHandler.h.
EndFragment()
void opendnp3::PrintingSOEHandler::EndFragment (const ResponseInfo & info) override virtual
Implements opendnp3::ISOEHandler.
GetTimeString()
static std::string opendnp3::PrintingSOEHandler::GetTimeString (TimestampQuality tsquality) inline static private
Definition at line 82 of file PrintingSOEHandler.h.
References opendnp3::SYNCHRONIZED, and opendnp3::UNSYNCHRONIZED.
Print()
template<class T > static void opendnp3::PrintingSOEHandler::Print (const HeaderInfo & info, const T & value, uint16_t index) inline static private
Definition at line 69 of file PrintingSOEHandler.h.
References ValueToString().
PrintAll()
template<class T > static void opendnp3::PrintingSOEHandler::PrintAll (const HeaderInfo & info, const ICollection< Indexed< T >> & values) inline static private
Definition at line 63 of file PrintingSOEHandler.h.
Process() [1/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< DNPTime > & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [2/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< Analog >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [3/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< AnalogCommandEvent >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [4/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< AnalogOutputStatus >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [5/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< Binary >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [6/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< BinaryCommandEvent >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [7/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< BinaryOutputStatus >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [8/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< Counter >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [9/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< DoubleBitBinary >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [10/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< FrozenCounter >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [11/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< OctetString >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [12/12]
virtual void opendnp3::PrintingSOEHandler::Process (const HeaderInfo & info, const ICollection< Indexed< TimeAndInterval >> & values) override virtual
Implements opendnp3::ISOEHandler.
ValueToString() [1/2]
static std::string opendnp3::PrintingSOEHandler::ValueToString (const DoubleBitBinary & meas) inline static private
Definition at line 101 of file PrintingSOEHandler.h.
References opendnp3::DoubleBitSpec::to_human_string(), and opendnp3::TypedMeasurement< T >::value.
ValueToString() [2/2]
template<class T > static std::string opendnp3::PrintingSOEHandler::ValueToString (const T & meas) inline static private
Definition at line 75 of file PrintingSOEHandler.h.
Referenced by Print().
The documentation for this class was generated from the following file:
opendnp3/master/PrintingSOEHandler.h