opendnp3: opendnp3::measurements::IsEvent
template<class T , class U > bool opendnp3::measurements::IsEvent (const T & val1, const T & val2, T deadband)
Definition at line 31 of file EventTriggers.h.
Referenced by opendnp3::SimpleEventCell< Spec >::IsEvent(), opendnp3::DeadbandEventCell< Spec >::IsEvent(), opendnp3::AnalogSpec::IsEvent(), and opendnp3::AnalogOutputStatusSpec::IsEvent().
 {
     // T can be unsigned data type so std::abs won't work since it only directly supports signed data types
     // If one uses std::abs and T is unsigned one will get an ambiguous override error.
     U diff = (val2 > val1) ? (static_cast<U>(val2) - static_cast<U>(val1)) : (static_cast<U>(val1) - static_cast<U>(val2));
     return diff > deadband;
 }