opendnp3: asiopal::Executor Class Reference
asiopal::Executor Class Reference final
Implementation of openpal::IExecutor backed by asio::strand.
#include <Executor.h>
Public Member Functions
Executor (const std::shared_ptr< IO > &io)
void BlockUntil (const std::function< void()> &action)
void BlockUntilAndFlush (const std::function< void()> &action)
std::shared_ptr< Executor > Fork () const
virtual openpal::MonotonicTimestamp GetTime () override
-— Implement IExecutor --—
virtual void Post (const openpal::action_t &runnable) override
template<class T >
T ReturnFrom (const std::function< T()> &action)
virtual openpal::ITimer * Start (const openpal::TimeDuration &, const openpal::action_t &runnable) override
virtual openpal::ITimer * Start (const openpal::MonotonicTimestamp &, const openpal::action_t &runnable) override
Public Member Functions inherited from openpal::IExecutor
virtual ~IExecutor ()
Public Member Functions inherited from openpal::IMonotonicTimeSource
virtual ~IMonotonicTimeSource ()
Static Public Member Functions
static std::shared_ptr< Executor > Create (const std::shared_ptr< IO > &io)
Public Attributes
asio::io_context::strand strand
Private Member Functions
openpal::ITimer * Start (const steady_clock_t::time_point &expiration, const openpal::action_t &runnable)
Private Member Functions inherited from openpal::Uncopyable
Uncopyable ()
~Uncopyable ()
Private Attributes
std::shared_ptr< IO > io
Detailed Description
Implementation of openpal::IExecutor backed by asio::strand.
Shutdown life-cycle guarantees are provided by using std::shared_ptr
Definition at line 41 of file Executor.h.
Constructor & Destructor Documentation
Executor()
asiopal::Executor::Executor (const std::shared_ptr< IO > & io)
Member Function Documentation
BlockUntil()
void asiopal::Executor::BlockUntil (const std::function< void()> & action)
BlockUntilAndFlush()
void asiopal::Executor::BlockUntilAndFlush (const std::function< void()> & action)
Create()
static std::shared_ptr<Executor> asiopal::Executor::Create (const std::shared_ptr< IO > & io) inline static
Definition at line 49 of file Executor.h.
References io.
Referenced by asiopal::ThreadPool::CreateExecutor(), and Fork().
Fork()
std::shared_ptr<Executor> asiopal::Executor::Fork () const inline
Definition at line 73 of file Executor.h.
References Create().
GetTime()
virtual openpal::MonotonicTimestamp asiopal::Executor::GetTime () override virtual
-— Implement IExecutor --—
Implements openpal::IMonotonicTimeSource.
Post()
virtual void asiopal::Executor::Post (const openpal::action_t & action) override virtual
Returns
Thread-safe way to post an event to be handled asynchronously
Implements openpal::IExecutor.
ReturnFrom()
template<class T > T asiopal::Executor::ReturnFrom (const std::function< T()> & action)
Definition at line 84 of file Executor.h.
References strand.
Start() [1/3]
virtual openpal::ITimer* asiopal::Executor::Start (const openpal::TimeDuration & duration, const openpal::action_t & action) override virtual
Returns
a new timer based on a relative time duration
Implements openpal::IExecutor.
Start() [2/3]
virtual openpal::ITimer* asiopal::Executor::Start (const openpal::MonotonicTimestamp & expiration, const openpal::action_t & action) override virtual
Returns
a new timer based on an absolute timestamp of the monotonic clock
Implements openpal::IExecutor.
Start() [3/3]
openpal::ITimer* asiopal::Executor::Start (const steady_clock_t::time_point & expiration, const openpal::action_t & runnable) private
Member Data Documentation
io
std::shared_ptr<IO> asiopal::Executor::io private
Definition at line 69 of file Executor.h.
Referenced by Create().
strand
asio::io_context::strand asiopal::Executor::strand
Definition at line 78 of file Executor.h.
Referenced by ReturnFrom().
The documentation for this class was generated from the following file:
cpp/libs/include/asiopal/Executor.h