opendnp3: opendnp3::Transaction Class Reference
opendnp3::Transaction Class Reference
Uses RAII to safely perform a transaction.
#include <ITransactable.h>
Public Member Functions
Transaction (ITransactable &transactable)
Transaction (ITransactable *pTransactable_)
~Transaction ()
Static Public Member Functions
template<class ReturnType , class TransactionType , class Fun >
static ReturnType Apply (TransactionType &transactable, const Fun &fun)
static void End (ITransactable *t)
static void Start (ITransactable *t)
Private Attributes
ITransactable * pTransactable
Additional Inherited Members
Private Member Functions inherited from openpal::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Uses RAII to safely perform a transaction.
Definition at line 45 of file ITransactable.h.
Constructor & Destructor Documentation
Transaction() [1/2]
opendnp3::Transaction::Transaction (ITransactable & transactable) inline
Definition at line 48 of file ITransactable.h.
References pTransactable, and opendnp3::ITransactable::Start().
Transaction() [2/2]
opendnp3::Transaction::Transaction (ITransactable * pTransactable_) inline
Definition at line 53 of file ITransactable.h.
References pTransactable, and opendnp3::ITransactable::Start().
~Transaction()
opendnp3::Transaction::~Transaction () inline
Definition at line 61 of file ITransactable.h.
References opendnp3::ITransactable::End(), and pTransactable.
Member Function Documentation
Apply()
template<class ReturnType , class TransactionType , class Fun > static ReturnType opendnp3::Transaction::Apply (TransactionType & transactable, const Fun & fun) inline static
Definition at line 85 of file ITransactable.h.
End()
static void opendnp3::Transaction::End (ITransactable * t) inline static
Definition at line 76 of file ITransactable.h.
References opendnp3::ITransactable::End().
Start()
static void opendnp3::Transaction::Start (ITransactable * t) inline static
Definition at line 69 of file ITransactable.h.
References opendnp3::ITransactable::Start().
Member Data Documentation
pTransactable
ITransactable* opendnp3::Transaction::pTransactable private
Definition at line 92 of file ITransactable.h.
Referenced by Transaction(), and ~Transaction().
The documentation for this class was generated from the following file:
cpp/libs/include/opendnp3/app/ITransactable.h