opendnp3: openpal::UInt48LE Class Reference
openpal::UInt48LE Class Reference
#include <UInt48LE.h>
Public Types
typedef UInt48Type Type
Static Public Member Functions
static UInt48Type Read (const uint8_t *data)
static UInt48Type ReadBuffer (RSlice &buffer)
static void Write (uint8_t *data, UInt48Type value)
static void WriteBuffer (WSlice &buffer, UInt48Type value)
Static Public Attributes
const static int64_t MAX = 281474976710655ULL
const static size_t SIZE = 6
Detailed Description
Definition at line 34 of file UInt48LE.h.
Member Typedef Documentation
Type
typedef UInt48Type openpal::UInt48LE::Type
Definition at line 56 of file UInt48LE.h.
Member Function Documentation
Read()
static UInt48Type openpal::UInt48LE::Read (const uint8_t * data) static
Referenced by ReadBuffer().
ReadBuffer()
static UInt48Type openpal::UInt48LE::ReadBuffer (RSlice & buffer) inline static
Definition at line 41 of file UInt48LE.h.
References openpal::RSlice::Advance(), Read(), and SIZE.
Write()
static void openpal::UInt48LE::Write (uint8_t * data, UInt48Type value) static
Referenced by WriteBuffer().
WriteBuffer()
static void openpal::UInt48LE::WriteBuffer (WSlice & buffer, UInt48Type value) inline static
Definition at line 48 of file UInt48LE.h.
References openpal::WSlice::Advance(), SIZE, and Write().
Member Data Documentation
MAX
const static int64_t openpal::UInt48LE::MAX = 281474976710655ULL static
Definition at line 54 of file UInt48LE.h.
SIZE
const static size_t openpal::UInt48LE::SIZE = 6 static
Definition at line 55 of file UInt48LE.h.
Referenced by ReadBuffer(), and WriteBuffer().
The documentation for this class was generated from the following file:
cpp/libs/include/openpal/serialization/UInt48LE.h