opendnp3: asiopal::TCPClient::Create
static std::shared_ptr<TCPClient> asiopal::TCPClient::Create (const openpal::Logger & logger, const std::shared_ptr< Executor > & executor, const IPEndpoint & remote, const std::string & adapter) inline static
Definition at line 38 of file TCPClient.h.
References adapter, BeginConnect(), Cancel(), executor, HandleResolveResult(), PostConnectError(), and TCPClient().
     {
         return std::make_shared<TCPClient>(logger, executor, remote, adapter);
     }