opendnp3: asiodnp3::DefaultListenCallbacks::~DefaultListenCallbacks
virtual asiodnp3::DefaultListenCallbacks::~DefaultListenCallbacks () inline virtual
Definition at line 40 of file DefaultListenCallbacks.h.
References AcceptCertificate(), AcceptConnection(), GetFirstFrameTimeout(), OnCertificateError(), OnConnectionClose(), OnFirstFrame(), and SessionIdToString().
 {}