opendnp3: opendnp3::Flags Class Reference
opendnp3::Flags Class Reference
Measurement Flags.
#include <opendnp3/app/Flags.h>
Public Member Functions
Flags ()
Flags (uint8_t value)
bool IsSet (AnalogOutputStatusQuality flag) const
bool IsSet (AnalogQuality flag) const
bool IsSet (BinaryOutputStatusQuality flag) const
bool IsSet (BinaryQuality flag) const
bool IsSet (CounterQuality flag) const
bool IsSet (DoubleBitBinaryQuality flag) const
bool IsSet (FrozenCounterQuality flag) const
void Set (AnalogOutputStatusQuality flag)
void Set (AnalogQuality flag)
void Set (BinaryOutputStatusQuality flag)
void Set (BinaryQuality flag)
void Set (CounterQuality flag)
void Set (DoubleBitBinaryQuality flag)
void Set (FrozenCounterQuality flag)
Public Attributes
uint8_t value
Protected Member Functions
template<class T >
bool IsSetAny (T flag) const
template<class T >
void SetAny (T flag)
Detailed Description
Measurement Flags.
Definition at line 37 of file Flags.h.
Constructor & Destructor Documentation
Flags() [1/2]
opendnp3::Flags::Flags () inline
Definition at line 40 of file Flags.h.
Flags() [2/2]
opendnp3::Flags::Flags (uint8_t value) inline explicit
Definition at line 42 of file Flags.h.
Member Function Documentation
IsSet() [1/7]
bool opendnp3::Flags::IsSet (AnalogOutputStatusQuality flag) const inline
Definition at line 68 of file Flags.h.
References IsSetAny().
IsSet() [2/7]
bool opendnp3::Flags::IsSet (AnalogQuality flag) const inline
Definition at line 52 of file Flags.h.
References IsSetAny().
IsSet() [3/7]
bool opendnp3::Flags::IsSet (BinaryOutputStatusQuality flag) const inline
Definition at line 64 of file Flags.h.
References IsSetAny().
IsSet() [4/7]
bool opendnp3::Flags::IsSet (BinaryQuality flag) const inline
Definition at line 44 of file Flags.h.
References IsSetAny().
IsSet() [5/7]
bool opendnp3::Flags::IsSet (CounterQuality flag) const inline
Definition at line 56 of file Flags.h.
References IsSetAny().
IsSet() [6/7]
bool opendnp3::Flags::IsSet (DoubleBitBinaryQuality flag) const inline
Definition at line 48 of file Flags.h.
References IsSetAny().
IsSet() [7/7]
bool opendnp3::Flags::IsSet (FrozenCounterQuality flag) const inline
Definition at line 60 of file Flags.h.
References IsSetAny().
IsSetAny()
template<class T > bool opendnp3::Flags::IsSetAny (T flag) const inline protected
Definition at line 105 of file Flags.h.
References value.
Referenced by IsSet().
Set() [1/7]
void opendnp3::Flags::Set (AnalogOutputStatusQuality flag) inline
Definition at line 97 of file Flags.h.
References SetAny().
Set() [2/7]
void opendnp3::Flags::Set (AnalogQuality flag) inline
Definition at line 81 of file Flags.h.
References SetAny().
Set() [3/7]
void opendnp3::Flags::Set (BinaryOutputStatusQuality flag) inline
Definition at line 93 of file Flags.h.
References SetAny().
Set() [4/7]
void opendnp3::Flags::Set (BinaryQuality flag) inline
Definition at line 73 of file Flags.h.
References SetAny().
Set() [5/7]
void opendnp3::Flags::Set (CounterQuality flag) inline
Definition at line 85 of file Flags.h.
References SetAny().
Set() [6/7]
void opendnp3::Flags::Set (DoubleBitBinaryQuality flag) inline
Definition at line 77 of file Flags.h.
References SetAny().
Set() [7/7]
void opendnp3::Flags::Set (FrozenCounterQuality flag) inline
Definition at line 89 of file Flags.h.
References SetAny().
SetAny()
template<class T > void opendnp3::Flags::SetAny (T flag) inline protected
Definition at line 110 of file Flags.h.
References value.
Referenced by Set().
Member Data Documentation
value
uint8_t opendnp3::Flags::value
Definition at line 102 of file Flags.h.
Referenced by IsSetAny(), and SetAny().
The documentation for this class was generated from the following file:
opendnp3/app/Flags.h