opendnp3: openpal::Bit32LE< T > Class Template Reference
openpal::Bit32LE< T > Class Template Reference
#include <SerializationTemplatesLE.h>
Public Types
typedef T Type
Static Public Member Functions
static T Read (const uint8_t *data)
static T ReadBuffer (RSlice &buffer)
static void Write (uint8_t *data, T value)
static void WriteBuffer (WSlice &buffer, T aValue)
Static Public Attributes
const static T Max = openpal::MaxValue<T>()
const static T Min = openpal::MinValue<T>()
const static size_t SIZE = sizeof(T)
Detailed Description
template<class T>
class openpal::Bit32LE< T >
Definition at line 71 of file SerializationTemplatesLE.h.
Member Typedef Documentation
Type
template<class T > typedef T openpal::Bit32LE< T >::Type
Definition at line 106 of file SerializationTemplatesLE.h.
Member Function Documentation
Read()
template<class T > static T openpal::Bit32LE< T >::Read (const uint8_t * data) inline static
Definition at line 79 of file SerializationTemplatesLE.h.
Referenced by openpal::Bit32LE< T >::ReadBuffer().
ReadBuffer()
template<class T > static T openpal::Bit32LE< T >::ReadBuffer (RSlice & buffer) inline static
Definition at line 99 of file SerializationTemplatesLE.h.
References openpal::RSlice::Advance(), openpal::Bit32LE< T >::Read(), and openpal::Bit32LE< T >::SIZE.
Write()
template<class T > static void openpal::Bit32LE< T >::Write (uint8_t * data, T value) inline static
Definition at line 85 of file SerializationTemplatesLE.h.
Referenced by openpal::Bit32LE< T >::WriteBuffer().
WriteBuffer()
template<class T > static void openpal::Bit32LE< T >::WriteBuffer (WSlice & buffer, T aValue) inline static
Definition at line 93 of file SerializationTemplatesLE.h.
References openpal::WSlice::Advance(), openpal::Bit32LE< T >::SIZE, and openpal::Bit32LE< T >::Write().
Member Data Documentation
Max
template<class T > const T openpal::Bit32LE< T >::Max = openpal::MaxValue<T>() static
Definition at line 109 of file SerializationTemplatesLE.h.
Min
template<class T > const T openpal::Bit32LE< T >::Min = openpal::MinValue<T>() static
Definition at line 110 of file SerializationTemplatesLE.h.
SIZE
template<class T > const static size_t openpal::Bit32LE< T >::SIZE = sizeof(T) static
Definition at line 108 of file SerializationTemplatesLE.h.
Referenced by openpal::Bit32LE< T >::ReadBuffer(), and openpal::Bit32LE< T >::WriteBuffer().
The documentation for this class was generated from the following file:
cpp/libs/include/openpal/serialization/SerializationTemplatesLE.h