opendnp3: opendnp3::ICommandProcessor Class Reference
opendnp3::ICommandProcessor Class Reference abstract
Interface used to dispatch SELECT / OPERATE / DIRECT OPERATE from application code to a master.
#include <opendnp3/master/ICommandProcessor.h>
Public Member Functions
virtual void DirectOperate (CommandSet &&commands, const CommandResultCallbackT &callback, const TaskConfig &config=TaskConfig::Default())=0
Direct operate a set of commands.
template<class T >
void DirectOperate (const T &command, uint16_t index, const CommandResultCallbackT &callback, const TaskConfig &config=TaskConfig::Default())
Direct operate a single command.
virtual void SelectAndOperate (CommandSet &&commands, const CommandResultCallbackT &callback, const TaskConfig &config=TaskConfig::Default())=0
Select and operate a set of commands.
template<class T >
void SelectAndOperate (const T &command, uint16_t index, const CommandResultCallbackT &callback, const TaskConfig &config=TaskConfig::Default())
Select/operate a single command.
Detailed Description
Interface used to dispatch SELECT / OPERATE / DIRECT OPERATE from application code to a master.
Definition at line 33 of file ICommandProcessor.h.
Member Function Documentation
DirectOperate() [1/2]
virtual void opendnp3::ICommandProcessor::DirectOperate (CommandSet && commands, const CommandResultCallbackT & callback, const TaskConfig & config = TaskConfig::Default()) pure virtual
Direct operate a set of commands.
Parameters
commands Set of command headers
callback callback that will be invoked upon completion or failure
config optional configuration that controls normal callbacks and allows the user to be specified for SA
Referenced by DirectOperate().
DirectOperate() [2/2]
template<class T > void opendnp3::ICommandProcessor::DirectOperate (const T & command, uint16_t index, const CommandResultCallbackT & callback, const TaskConfig & config = TaskConfig::Default())
Direct operate a single command.
Parameters
command Command to operate
index of the command
callback callback that will be invoked upon completion or failure
config optional configuration that controls normal callbacks and allows the user to be specified for SA
Definition at line 100 of file ICommandProcessor.h.
References DirectOperate(), and opendnp3::WithIndex().
SelectAndOperate() [1/2]
virtual void opendnp3::ICommandProcessor::SelectAndOperate (CommandSet && commands, const CommandResultCallbackT & callback, const TaskConfig & config = TaskConfig::Default()) pure virtual
Select and operate a set of commands.
Parameters
commands Set of command headers
callback callback that will be invoked upon completion or failure
config optional configuration that controls normal callbacks and allows the user to be specified for SA
Referenced by SelectAndOperate().
SelectAndOperate() [2/2]
template<class T > void opendnp3::ICommandProcessor::SelectAndOperate (const T & command, uint16_t index, const CommandResultCallbackT & callback, const TaskConfig & config = TaskConfig::Default())
Select/operate a single command.
Parameters
command Command to operate
index of the command
callback callback that will be invoked upon completion or failure
config optional configuration that controls normal callbacks and allows the user to be specified for SA
Definition at line 90 of file ICommandProcessor.h.
References SelectAndOperate(), and opendnp3::WithIndex().
The documentation for this class was generated from the following file:
opendnp3/master/ICommandProcessor.h