opendnp3: openpal::UInt8Simple Class Reference
openpal::UInt8Simple Class Reference
#include <ByteSerialization.h>
Public Types
typedef uint8_t Type
Static Public Member Functions
static uint8_t Read (const uint8_t *pStart)
static uint8_t ReadBuffer (RSlice &buffer)
static void Write (uint8_t *pStart, uint8_t value)
static void WriteBuffer (WSlice &buffer, uint8_t value)
Static Public Attributes
const static uint8_t Max
const static uint8_t Min
const static size_t SIZE = 1
Detailed Description
Definition at line 32 of file ByteSerialization.h.
Member Typedef Documentation
Type
typedef uint8_t openpal::UInt8Simple::Type
Definition at line 62 of file ByteSerialization.h.
Member Function Documentation
Read()
static uint8_t openpal::UInt8Simple::Read (const uint8_t * pStart) inline static
Definition at line 35 of file ByteSerialization.h.
Referenced by ReadBuffer().
ReadBuffer()
static uint8_t openpal::UInt8Simple::ReadBuffer (RSlice & buffer) inline static
Definition at line 40 of file ByteSerialization.h.
References openpal::RSlice::Advance(), Read(), and SIZE.
Write()
static void openpal::UInt8Simple::Write (uint8_t * pStart, uint8_t value) inline static
Definition at line 53 of file ByteSerialization.h.
Referenced by WriteBuffer().
WriteBuffer()
static void openpal::UInt8Simple::WriteBuffer (WSlice & buffer, uint8_t value) inline static
Definition at line 47 of file ByteSerialization.h.
References openpal::WSlice::Advance(), SIZE, and Write().
Member Data Documentation
Max
const static uint8_t openpal::UInt8Simple::Max static
Definition at line 59 of file ByteSerialization.h.
Min
const static uint8_t openpal::UInt8Simple::Min static
Definition at line 60 of file ByteSerialization.h.
SIZE
const static size_t openpal::UInt8Simple::SIZE = 1 static
Definition at line 58 of file ByteSerialization.h.
Referenced by ReadBuffer(), and WriteBuffer().
The documentation for this class was generated from the following file:
cpp/libs/include/openpal/serialization/ByteSerialization.h