opendnp3: openpal::TimerRef Class Reference
openpal::TimerRef Class Reference
A management class to make dealing with timer pointers safer a little safer.
#include <TimerRef.h>
Public Member Functions
TimerRef (openpal::IExecutor &executor)
~TimerRef ()
bool Cancel ()
MonotonicTimestamp ExpiresAt () const
bool IsActive () const
template<class Lambda >
void Restart (const TimeDuration &expiration, const Lambda &action)
template<class Lambda >
void Restart (const MonotonicTimestamp &expiration, const Lambda &action)
template<class Lambda >
bool Start (const TimeDuration &timeout, const Lambda &action)
template<class Lambda >
bool Start (const MonotonicTimestamp &expiration, const Lambda &action)
Private Member Functions
void RestartAction (const TimeDuration &timeout, const action_t &action)
void RestartAction (const MonotonicTimestamp &expiration, const action_t &action)
bool StartAction (const TimeDuration &timeout, const action_t &action)
bool StartAction (const MonotonicTimestamp &expiration, const action_t &action)
Private Member Functions inherited from openpal::Uncopyable
Uncopyable ()
~Uncopyable ()
Private Attributes
IExecutor * pExecutor
ITimer * pTimer
Detailed Description
A management class to make dealing with timer pointers safer a little safer.
Holds an optional pointer to an active ITimer pointer. Acts as a safe proxy for dealing with a recurring timer instance.
Definition at line 36 of file TimerRef.h.
Constructor & Destructor Documentation
TimerRef()
openpal::TimerRef::TimerRef (openpal::IExecutor & executor)
~TimerRef()
openpal::TimerRef::~TimerRef ()
Member Function Documentation
Cancel()
bool openpal::TimerRef::Cancel ()
ExpiresAt()
MonotonicTimestamp openpal::TimerRef::ExpiresAt () const
IsActive()
bool openpal::TimerRef::IsActive () const
Restart() [1/2]
template<class Lambda > void openpal::TimerRef::Restart (const TimeDuration & expiration, const Lambda & action)
Definition at line 98 of file TimerRef.h.
References pTimer, and RestartAction().
Restart() [2/2]
template<class Lambda > void openpal::TimerRef::Restart (const MonotonicTimestamp & expiration, const Lambda & action)
Definition at line 107 of file TimerRef.h.
References pTimer, and RestartAction().
RestartAction() [1/2]
void openpal::TimerRef::RestartAction (const TimeDuration & timeout, const action_t & action) private
Referenced by Restart().
RestartAction() [2/2]
void openpal::TimerRef::RestartAction (const MonotonicTimestamp & expiration, const action_t & action) private
Start() [1/2]
template<class Lambda > bool openpal::TimerRef::Start (const TimeDuration & timeout, const Lambda & action)
Definition at line 80 of file TimerRef.h.
References pTimer, and StartAction().
Start() [2/2]
template<class Lambda > bool openpal::TimerRef::Start (const MonotonicTimestamp & expiration, const Lambda & action)
Definition at line 89 of file TimerRef.h.
References pTimer, and StartAction().
StartAction() [1/2]
bool openpal::TimerRef::StartAction (const TimeDuration & timeout, const action_t & action) private
Referenced by Start().
StartAction() [2/2]
bool openpal::TimerRef::StartAction (const MonotonicTimestamp & expiration, const action_t & action) private
Member Data Documentation
pExecutor
IExecutor* openpal::TimerRef::pExecutor private
Definition at line 74 of file TimerRef.h.
pTimer
ITimer* openpal::TimerRef::pTimer private
Definition at line 75 of file TimerRef.h.
Referenced by Restart(), and Start().
The documentation for this class was generated from the following file:
cpp/libs/include/openpal/executor/TimerRef.h