opendnp3: opendnp3::DatabaseSizes Struct Reference
opendnp3::DatabaseSizes Struct Reference
Specifies the number and type of measurements in an outstation database.
#include <DatabaseSizes.h>
Public Member Functions
DatabaseSizes (uint16_t numBinary, uint16_t numDoubleBinary, uint16_t numAnalog, uint16_t numCounter, uint16_t numFrozenCounter, uint16_t numBinaryOutputStatus, uint16_t numAnalogOutputStatus, uint16_t numTimeAndInterval, uint16_t numOctetString)
Static Public Member Functions
static DatabaseSizes AllTypes (uint16_t count)
static DatabaseSizes AnalogOnly (uint16_t count)
static DatabaseSizes AnalogOutputStatusOnly (uint16_t count)
static DatabaseSizes BinaryOnly (uint16_t count)
static DatabaseSizes BinaryOutputStatusOnly (uint16_t count)
static DatabaseSizes CounterOnly (uint16_t count)
static DatabaseSizes DoubleBinaryOnly (uint16_t count)
static DatabaseSizes Empty ()
static DatabaseSizes FrozenCounterOnly (uint16_t count)
static DatabaseSizes OctetStringOnly (uint16_t count)
static DatabaseSizes TimeAndIntervalOnly (uint16_t count)
Public Attributes
uint16_t numAnalog
uint16_t numAnalogOutputStatus
uint16_t numBinary
uint16_t numBinaryOutputStatus
uint16_t numCounter
uint16_t numDoubleBinary
uint16_t numFrozenCounter
uint16_t numOctetString
uint16_t numTimeAndInterval
Detailed Description
Specifies the number and type of measurements in an outstation database.
Definition at line 31 of file DatabaseSizes.h.
Constructor & Destructor Documentation
DatabaseSizes()
opendnp3::DatabaseSizes::DatabaseSizes (uint16_t numBinary, uint16_t numDoubleBinary, uint16_t numAnalog, uint16_t numCounter, uint16_t numFrozenCounter, uint16_t numBinaryOutputStatus, uint16_t numAnalogOutputStatus, uint16_t numTimeAndInterval, uint16_t numOctetString) inline
Definition at line 88 of file DatabaseSizes.h.
Referenced by AllTypes(), AnalogOnly(), AnalogOutputStatusOnly(), BinaryOnly(), BinaryOutputStatusOnly(), CounterOnly(), DoubleBinaryOnly(), Empty(), FrozenCounterOnly(), OctetStringOnly(), and TimeAndIntervalOnly().
Member Function Documentation
AllTypes()
static DatabaseSizes opendnp3::DatabaseSizes::AllTypes (uint16_t count) inline static
Definition at line 78 of file DatabaseSizes.h.
References DatabaseSizes().
AnalogOnly()
static DatabaseSizes opendnp3::DatabaseSizes::AnalogOnly (uint16_t count) inline static
Definition at line 43 of file DatabaseSizes.h.
References DatabaseSizes().
AnalogOutputStatusOnly()
static DatabaseSizes opendnp3::DatabaseSizes::AnalogOutputStatusOnly (uint16_t count) inline static
Definition at line 63 of file DatabaseSizes.h.
References DatabaseSizes().
BinaryOnly()
static DatabaseSizes opendnp3::DatabaseSizes::BinaryOnly (uint16_t count) inline static
Definition at line 33 of file DatabaseSizes.h.
References DatabaseSizes().
BinaryOutputStatusOnly()
static DatabaseSizes opendnp3::DatabaseSizes::BinaryOutputStatusOnly (uint16_t count) inline static
Definition at line 58 of file DatabaseSizes.h.
References DatabaseSizes().
CounterOnly()
static DatabaseSizes opendnp3::DatabaseSizes::CounterOnly (uint16_t count) inline static
Definition at line 48 of file DatabaseSizes.h.
References DatabaseSizes().
DoubleBinaryOnly()
static DatabaseSizes opendnp3::DatabaseSizes::DoubleBinaryOnly (uint16_t count) inline static
Definition at line 38 of file DatabaseSizes.h.
References DatabaseSizes().
Empty()
static DatabaseSizes opendnp3::DatabaseSizes::Empty () inline static
Definition at line 83 of file DatabaseSizes.h.
References DatabaseSizes().
FrozenCounterOnly()
static DatabaseSizes opendnp3::DatabaseSizes::FrozenCounterOnly (uint16_t count) inline static
Definition at line 53 of file DatabaseSizes.h.
References DatabaseSizes().
OctetStringOnly()
static DatabaseSizes opendnp3::DatabaseSizes::OctetStringOnly (uint16_t count) inline static
Definition at line 73 of file DatabaseSizes.h.
References DatabaseSizes().
TimeAndIntervalOnly()
static DatabaseSizes opendnp3::DatabaseSizes::TimeAndIntervalOnly (uint16_t count) inline static
Definition at line 68 of file DatabaseSizes.h.
References DatabaseSizes().
Member Data Documentation
numAnalog
uint16_t opendnp3::DatabaseSizes::numAnalog
Definition at line 113 of file DatabaseSizes.h.
numAnalogOutputStatus
uint16_t opendnp3::DatabaseSizes::numAnalogOutputStatus
Definition at line 117 of file DatabaseSizes.h.
numBinary
uint16_t opendnp3::DatabaseSizes::numBinary
Definition at line 111 of file DatabaseSizes.h.
numBinaryOutputStatus
uint16_t opendnp3::DatabaseSizes::numBinaryOutputStatus
Definition at line 116 of file DatabaseSizes.h.
numCounter
uint16_t opendnp3::DatabaseSizes::numCounter
Definition at line 114 of file DatabaseSizes.h.
numDoubleBinary
uint16_t opendnp3::DatabaseSizes::numDoubleBinary
Definition at line 112 of file DatabaseSizes.h.
numFrozenCounter
uint16_t opendnp3::DatabaseSizes::numFrozenCounter
Definition at line 115 of file DatabaseSizes.h.
numOctetString
uint16_t opendnp3::DatabaseSizes::numOctetString
Definition at line 119 of file DatabaseSizes.h.
numTimeAndInterval
uint16_t opendnp3::DatabaseSizes::numTimeAndInterval
Definition at line 118 of file DatabaseSizes.h.
The documentation for this struct was generated from the following file:
cpp/libs/include/opendnp3/outstation/DatabaseSizes.h