opendnp3: openpal::RingBuffer::PutMany
template<uint8_t N> volatile uint8_t openpal::RingBuffer< N >::PutMany (RSlice & input) inline
Definition at line 86 of file RingBuffer.h.
References openpal::RSlice::Advance(), openpal::RingBuffer< N >::buffer, openpal::RingBuffer< N >::Count(), openpal::RingBuffer< N >::head, and openpal::HasSize< SizeType >::Size().
     {
         uint8_t num = openpal::Min<uint32_t>(N - Count(), input.Size());
         for(uint8_t i = 0; i < num; ++i)
         {
             buffer[(head++) & (N - 1)] = input[i];
         }
         input.Advance(num);
         return num;
     }