opendnp3: asiodnp3::PrintingSOEHandler Class Reference
asiodnp3::PrintingSOEHandler Class Reference final
ISOEHandler singleton that prints to the console.
#include <PrintingSOEHandler.h>
Public Member Functions
PrintingSOEHandler ()
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::DNPTime > &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::Analog >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::AnalogCommandEvent >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::AnalogOutputStatus >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::Binary >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::BinaryCommandEvent >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::BinaryOutputStatus >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::Counter >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::DoubleBitBinary >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::FrozenCounter >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::OctetString >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::SecurityStat >> &values) override
virtual void Process (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::TimeAndInterval >> &values) override
Public Member Functions inherited from opendnp3::ISOEHandler
virtual ~ISOEHandler ()
Public Member Functions inherited from opendnp3::ITransactable
virtual ~ITransactable ()
Static Public Member Functions
static std::shared_ptr< ISOEHandler > Create ()
Protected Member Functions
void End () final
void Start () final
Static Private Member Functions
static std::string GetTimeString (opendnp3::TimestampMode tsmode)
template<class T >
static void Print (const opendnp3::HeaderInfo &info, const T &value, uint16_t index)
template<class T >
static void PrintAll (const opendnp3::HeaderInfo &info, const opendnp3::ICollection< opendnp3::Indexed< T >> &values)
static std::string ValueToString (const opendnp3::DoubleBitBinary &meas)
template<class T >
static std::string ValueToString (const T &meas)
Detailed Description
ISOEHandler singleton that prints to the console.
Definition at line 35 of file PrintingSOEHandler.h.
Constructor & Destructor Documentation
PrintingSOEHandler()
asiodnp3::PrintingSOEHandler::PrintingSOEHandler () inline
Definition at line 39 of file PrintingSOEHandler.h.
Member Function Documentation
Create()
static std::shared_ptr<ISOEHandler> asiodnp3::PrintingSOEHandler::Create () inline static
Definition at line 41 of file PrintingSOEHandler.h.
End()
void asiodnp3::PrintingSOEHandler::End () inline final protected virtual
Implements opendnp3::ITransactable.
Definition at line 75 of file PrintingSOEHandler.h.
GetTimeString()
static std::string asiodnp3::PrintingSOEHandler::GetTimeString (opendnp3::TimestampMode tsmode) inline static private
Definition at line 98 of file PrintingSOEHandler.h.
References opendnp3::SYNCHRONIZED, and opendnp3::UNSYNCHRONIZED.
Print()
template<class T > static void asiodnp3::PrintingSOEHandler::Print (const opendnp3::HeaderInfo & info, const T & value, uint16_t index) inline static private
Definition at line 85 of file PrintingSOEHandler.h.
References ValueToString().
PrintAll()
template<class T > static void asiodnp3::PrintingSOEHandler::PrintAll (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< T >> & values) inline static private
Definition at line 79 of file PrintingSOEHandler.h.
Process() [1/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::DNPTime > & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [2/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::Analog >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [3/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::AnalogCommandEvent >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [4/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::AnalogOutputStatus >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [5/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::Binary >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [6/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::BinaryCommandEvent >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [7/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::BinaryOutputStatus >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [8/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::Counter >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [9/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::DoubleBitBinary >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [10/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::FrozenCounter >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [11/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::OctetString >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [12/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::SecurityStat >> & values) override virtual
Implements opendnp3::ISOEHandler.
Process() [13/13]
virtual void asiodnp3::PrintingSOEHandler::Process (const opendnp3::HeaderInfo & info, const opendnp3::ICollection< opendnp3::Indexed< opendnp3::TimeAndInterval >> & values) override virtual
Implements opendnp3::ISOEHandler.
Start()
void asiodnp3::PrintingSOEHandler::Start () inline final protected virtual
Implements opendnp3::ITransactable.
Definition at line 74 of file PrintingSOEHandler.h.
ValueToString() [1/2]
static std::string asiodnp3::PrintingSOEHandler::ValueToString (const opendnp3::DoubleBitBinary & meas) inline static private
Definition at line 117 of file PrintingSOEHandler.h.
References opendnp3::DoubleBitToString(), and opendnp3::TypedMeasurement< T >::value.
ValueToString() [2/2]
template<class T > static std::string asiodnp3::PrintingSOEHandler::ValueToString (const T & meas) inline static private
Definition at line 91 of file PrintingSOEHandler.h.
Referenced by Print().
The documentation for this class was generated from the following file:
cpp/libs/include/asiodnp3/PrintingSOEHandler.h