opendnp3: openpal::ArrayView< T, W > Class Template Reference
openpal::ArrayView< T, W > Class Template Reference
Acts as a safe facade around an underlying array.
#include <ArrayView.h>
Public Member Functions
ArrayView (T *start, W size)
bool Contains (W index) const
bool Contains (W start, W stop) const
template<class Action >
void foreach (const Action &action)
T & operator[] (W index)
const T & operator[] (W index) const
Public Member Functions inherited from openpal::HasSize< W >
HasSize (W size)
bool IsEmpty () const
bool IsNotEmpty () const
W Size () const
Static Public Member Functions
static ArrayView< T, W > Empty ()
Private Attributes
T * buffer
Additional Inherited Members
Protected Attributes inherited from openpal::HasSize< W >
W size
Detailed Description
template<class T, class W>
class openpal::ArrayView< T, W >
Acts as a safe facade around an underlying array.
Definition at line 33 of file ArrayView.h.
Constructor & Destructor Documentation
ArrayView()
template<class T , class W > openpal::ArrayView< T, W >::ArrayView (T * start, W size) inline
Definition at line 42 of file ArrayView.h.
Referenced by openpal::ArrayView< T, W >::Empty().
Member Function Documentation
Contains() [1/2]
template<class T , class W > bool openpal::ArrayView< T, W >::Contains (W index) const inline
Definition at line 44 of file ArrayView.h.
References openpal::HasSize< W >::size.
Referenced by openpal::ArrayView< T, W >::Contains().
Contains() [2/2]
template<class T , class W > bool openpal::ArrayView< T, W >::Contains (W start, W stop) const inline
Definition at line 49 of file ArrayView.h.
References openpal::ArrayView< T, W >::Contains().
Empty()
template<class T , class W > static ArrayView<T, W> openpal::ArrayView< T, W >::Empty () inline static
Definition at line 37 of file ArrayView.h.
References openpal::ArrayView< T, W >::ArrayView().
foreach()
template<class T , class W > template<class Action > void openpal::ArrayView< T, W >::foreach (const Action & action) inline
Definition at line 66 of file ArrayView.h.
References openpal::ArrayView< T, W >::buffer, and openpal::HasSize< W >::size.
operator[]() [1/2]
template<class T , class W > T& openpal::ArrayView< T, W >::operator[] (W index) inline
Definition at line 54 of file ArrayView.h.
References openpal::ArrayView< T, W >::buffer, and openpal::HasSize< W >::size.
operator[]() [2/2]
template<class T , class W > const T& openpal::ArrayView< T, W >::operator[] (W index) const inline
Definition at line 60 of file ArrayView.h.
References openpal::ArrayView< T, W >::buffer, and openpal::HasSize< W >::size.
Member Data Documentation
buffer
template<class T , class W > T* openpal::ArrayView< T, W >::buffer private
Definition at line 75 of file ArrayView.h.
Referenced by openpal::ArrayView< T, W >::foreach(), and openpal::ArrayView< T, W >::operator[]().
The documentation for this class was generated from the following file:
cpp/libs/include/openpal/container/ArrayView.h